### PR TITLE
Update login templates to PatternFly 4 design

### PR DESCRIPTION
**Pull request by rhamilto**
Important:  I need help testing these changes as I am unclear on how to go about doing so.

The templates should render as seen at:
* https://rhamilto.github.io/oauth-templates/okd/errors.html
* https://rhamilto.github.io/oauth-templates/okd/login.html
* https://rhamilto.github.io/oauth-templates/okd/providers.html

cc: @spadgett, @benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Screenshots maybe?  This is tricky to review :)

**Comment by benjaminapetersen** [comment]
@stlaz fyi

**Comment by benjaminapetersen** [comment]
@rhamilto this should prob do the job:
https://gist.github.com/benjaminapetersen/3259fd041d47925f66a064a59311d443
It involves setting the `authentication.operator` to `Unmanaged` and then overriding the `oauth-server` image.

**Comment by benjaminapetersen** [comment]
Cross reference for good measure:
- https://github.com/openshift/cluster-authentication-operator/pull/244
- https://github.com/rhamilto/oauth-templates (to move to openshift org?)

**Comment by rhamilto** [comment]
`ci/prow/e2e-aws-console-login` should pass once https://github.com/openshift/console/pull/4029 merges.

**Comment by stlaz** [comment]
/lgtm
appears to be working as expected

**Pull request merged**
