### PR TITLE
OCPBUGS-33695: fix nil deref in default auth handler

### PR DESCRIPTION
**Pull request by sjenning**
https://issues.redhat.com/browse/OCPBUGS-33695

### CODE REVIEW

**Comment by deads2k** [comment]
/approve
/hold

https://github.com/openshift/oauth-server/pull/150 looks like a better fix that retains most of the debugging info.  I've approved so @ibihim can select which fix he wants.

**Comment by ibihim** [comment]
We will move forward with #150 instead.

/unhold

**Comment by ibihim** [comment]
We will move forward with #150, as it keeps more information.

**Comment by ibihim** [comment]
https://github.com/openshift/oauth-server/pull/150#issuecomment-2162913876

/close

**Pull request closed without merging**
